# Permalinks
permalink:           pretty

# Setup
title:               Marcell Alves
tagline:             Desenvolvimento web, automação, design de software, testes
url:                 https://marcellalves.github.io/
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Marcell Alves
  url:               https://twitter.com/alvesmarcell
  email:             marcell.alves@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/marcellalves/marcellalves.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
